Chemistry = {
    "A": ("Aliphatic",),
    "C": ("Cysteine",),
    "D": ("Acceptor", "Negative"),
    "E": ("Acceptor", "Negative"),
    "F": ("Aromatic",),
    "G": ("Glycine",),
    "H": ("Histidine",),
    "I": ("Aliphatic",),
    "K": ("Donor", "Positive"),
    "L": ("Aliphatic",),
    "M": ("Aliphatic",),
    "N": ("Donor", "Acceptor"),
    "P": ("Proline",),
    "Q": ("Donor", "Acceptor"),
    "R": ("Donor", "Positive"),
    "S": ("Donor",),
    "T": ("Donor",),
    "V": ("Aliphatic",),
    "W": ("Aromatic",),
    "Y": ("Aromatic", "Donor"),     
    }

MolecularWeight = {
    "A": 89.0,
    "C": 121.0,
    "D": 132.0,
    "E": 147.0,
    "F": 165.0,
    "G": 75.0,
    "H": 155.0,
    "I": 131.0,
    "K": 146.0,
    "L": 131.0,
    "M": 149.0,
    "N": 132.0,
    "P": 115.0,
    "Q": 146.0,
    "R": 174.0,
    "S": 105.0,
    "T": 119.0,
    "V": 117.0,
    "W": 204.0,
    "Y": 181.0,         
    }

ThreeLetterCode = {
    'A': 'ALA',
    'C': 'CYS',
    'D': 'ASP',
    'E': 'GLU',
    'F': 'PHE',
    'G': 'GLY',
    'H': 'HIS',
    'I': 'ILE',
    'K': 'LYS',
    'L': 'LEU',
    'M': 'MET',
    'N': 'ASN',
    'P': 'PRO',
    'Q': 'GLN',
    'R': 'ARG',
    'S': 'SER',
    'T': 'THR',
    'V': 'VAL',
    'W': 'TRP',
    'Y': 'TYR',
}
