Chemistry = {
    "A": ("Aliphatic",),
    "C": ("Cysteine",),
    "D": ("Acceptor", "Negative"),
    "E": ("Acceptor", "Negative"),
    "F": ("Aromatic",),
    "G": ("Glycine",),
    "H": ("Histidine",),
    "I": ("Aliphatic",),
    "K": ("Donor", "Positive"),
    "L": ("Aliphatic",),
    "M": ("Aliphatic",),
    "N": ("Donor", "Acceptor"),
    "P": ("Proline",),
    "Q": ("Donor", "Acceptor"),
    "R": ("Donor", "Positive"),
    "S": ("Donor",),
    "T": ("Donor",),
    "V": ("Aliphatic",),
    "W": ("Aromatic",),
    "Y": ("Aromatic", "Donor"),     
    }

MolecularWeight = {
    "A": 89.0,
    "C": 121.0,
    "D": 132.0,
    "E": 147.0,
    "F": 165.0,
    "G": 75.0,
    "H": 155.0,
    "I": 131.0,
    "K": 146.0,
    "L": 131.0,
    "M": 149.0,
    "N": 132.0,
    "P": 115.0,
    "Q": 146.0,
    "R": 174.0,
    "S": 105.0,
    "T": 119.0,
    "V": 117.0,
    "W": 204.0,
    "Y": 181.0,         
    }

HydropathyIndex = {
    "A": 1.8,
    "C": 2.5,
    "D": -3.5,
    "E": -3.5,
    "F": 2.8,
    "G": -0.4,
    "H": -3.2,
    "I": 4.5,
    "K": -3.9,
    "L": 3.8,
    "M": 1.9,
    "N": -3.5,
    "P": 1.6,
    "Q": -3.5,
    "R": -4.5,
    "S": -0.8,
    "T": -0.7,
    "V": 4.2,
    "W": -0.9,
    "Y": -1.3,         
    }

IsoelectricPoint = {
    "A": 6.01,
    "C": 5.07,
    "D": 2.77,
    "E": 3.22,
    "F": 5.48,
    "G": 5.97,
    "H": 7.59,
    "I": 6.02,
    "K": 9.74,
    "L": 5.98,
    "M": 5.74,
    "N": 5.41,
    "P": 6.48,
    "Q": 5.65,
    "R": 10.76,
    "S": 5.68,
    "T": 5.87,
    "V": 5.97,
    "W": 5.89,
    "Y": 5.66,         
    }

ThreeLetterCode = {
    'A': 'ALA',
    'C': 'CYS',
    'D': 'ASP',
    'E': 'GLU',
    'F': 'PHE',
    'G': 'GLY',
    'H': 'HIS',
    'I': 'ILE',
    'K': 'LYS',
    'L': 'LEU',
    'M': 'MET',
    'N': 'ASN',
    'P': 'PRO',
    'Q': 'GLN',
    'R': 'ARG',
    'S': 'SER',
    'T': 'THR',
    'V': 'VAL',
    'W': 'TRP',
    'Y': 'TYR',
}
